name: Generate gas diff

inputs:
  workflowId:
    description: The workflow's file name or ID
    required: true
  token:
    description: The repository's github token
    default: ${{ github.token }}
    required: false
  report:
    description: Report freshly generated to compare to reference
    default: gasreport.ansi
    required: false

runs:
  using: node16
  main: dist/index.js
