name: Generate gas diff

inputs:
  token:
    description: github token
    required: true
  report:
    description: Report freshly generated to compare to reference
    required: false
    default: gasreport.ansi
  outReport:
    description: Report to save & upload for later
    required: false
    default: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}.gasreport.ansi
  refReport:
    description: Report previously saved to use as reference
    required: false
    default: ${{ github.base_ref }}.gasreport.ansi

runs:
  using: composite
  steps:
    - name: Download reference report
      if: github.event_name == 'pull_request'
      run: |
        RUN_ID=`gh run list --repo ${{ github.repository }} --branch ${{ github.base_ref }} --workflow '${{ github.workflow }}' --json 'conclusion,databaseId' --jq 'map(select(.conclusion=="success"))[0].databaseId'`
        gh run download ${RUN_ID} --repo ${{ github.repository }} -n gasreport
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      continue-on-error: true
      id: reference

    - name: Compare reports
      if: steps.reference.outcome == 'success' && github.event_name == 'pull_request'
      run: node scripts/index.js -o markdown ${{ inputs.refReport }} ${{ inputs.report }} >> $GITHUB_STEP_SUMMARY

    - name: Format output filename
      run: echo ::set-output name=out_report::"$(echo ${{ inputs.outReport }} | sed 's,/,-,g')"
      id: format

    - name: Rename report for upload
      run: mv ${{ inputs.report }} ${{ steps.format.outputs.out_report }}

    - name: Save report
      uses: actions/upload-artifact@v3
      with:
        name: gasreport
        path: ${{ steps.format.outputs.out_report }}
