name: Generate gas diff

inputs:
  token:
    description: github token
    required: true
  report:
    description: Report freshly generated to compare to reference
    required: false
    default: gasreport.ansi
  outReport:
    description: Report to save & upload for later
    required: false
    default: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}.gasreport.ansi
  refReport:
    description: Report previously saved to download & use as reference
    required: false
    default: ${{ github.base_ref }}.gasreport.ansi

runs:
  using: node16
  main: dist/index.js
